// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: api/proto/message/v1/message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for HeartbeatRequest
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_proto_message_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_message_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_proto_message_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The response message for OCPPMessage
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_proto_message_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_message_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_proto_message_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_message_v1_message_proto protoreflect.FileDescriptor

const file_api_proto_message_v1_message_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/message/v1/message.proto\x12\n" +
	"message.v1\"#\n" +
	"\aRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa9\x02\n" +
	"\vOCPPMessage\x12?\n" +
	"\x10HeartbeatRequest\x12\x13.message.v1.Request\x1a\x14.message.v1.Response\"\x00\x12D\n" +
	"\x15HeartbeatConfirmation\x12\x13.message.v1.Request\x1a\x14.message.v1.Response\"\x00\x12F\n" +
	"\x17BootNotificationRequest\x12\x13.message.v1.Request\x1a\x14.message.v1.Response\"\x00\x12K\n" +
	"\x1cBootNotificationConfirmation\x12\x13.message.v1.Request\x1a\x14.message.v1.Response\"\x00B=Z;github.com/squishmeist/ocpp-go/pkg/api/message/v1;messagepbb\x06proto3"

var (
	file_api_proto_message_v1_message_proto_rawDescOnce sync.Once
	file_api_proto_message_v1_message_proto_rawDescData []byte
)

func file_api_proto_message_v1_message_proto_rawDescGZIP() []byte {
	file_api_proto_message_v1_message_proto_rawDescOnce.Do(func() {
		file_api_proto_message_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_message_v1_message_proto_rawDesc), len(file_api_proto_message_v1_message_proto_rawDesc)))
	})
	return file_api_proto_message_v1_message_proto_rawDescData
}

var file_api_proto_message_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_message_v1_message_proto_goTypes = []any{
	(*Request)(nil),  // 0: message.v1.Request
	(*Response)(nil), // 1: message.v1.Response
}
var file_api_proto_message_v1_message_proto_depIdxs = []int32{
	0, // 0: message.v1.OCPPMessage.HeartbeatRequest:input_type -> message.v1.Request
	0, // 1: message.v1.OCPPMessage.HeartbeatConfirmation:input_type -> message.v1.Request
	0, // 2: message.v1.OCPPMessage.BootNotificationRequest:input_type -> message.v1.Request
	0, // 3: message.v1.OCPPMessage.BootNotificationConfirmation:input_type -> message.v1.Request
	1, // 4: message.v1.OCPPMessage.HeartbeatRequest:output_type -> message.v1.Response
	1, // 5: message.v1.OCPPMessage.HeartbeatConfirmation:output_type -> message.v1.Response
	1, // 6: message.v1.OCPPMessage.BootNotificationRequest:output_type -> message.v1.Response
	1, // 7: message.v1.OCPPMessage.BootNotificationConfirmation:output_type -> message.v1.Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_message_v1_message_proto_init() }
func file_api_proto_message_v1_message_proto_init() {
	if File_api_proto_message_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_message_v1_message_proto_rawDesc), len(file_api_proto_message_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_message_v1_message_proto_goTypes,
		DependencyIndexes: file_api_proto_message_v1_message_proto_depIdxs,
		MessageInfos:      file_api_proto_message_v1_message_proto_msgTypes,
	}.Build()
	File_api_proto_message_v1_message_proto = out.File
	file_api_proto_message_v1_message_proto_goTypes = nil
	file_api_proto_message_v1_message_proto_depIdxs = nil
}
