// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/proto/ocpp/v1/ocpp.proto

package ocpppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AzureMessage_HeartbeatRequest_FullMethodName = "/ocpp.v1.AzureMessage/HeartbeatRequest"
)

// AzureMessageClient is the client API for AzureMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AzureMessageClient interface {
	// Sends a heartbeat
	HeartbeatRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type azureMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewAzureMessageClient(cc grpc.ClientConnInterface) AzureMessageClient {
	return &azureMessageClient{cc}
}

func (c *azureMessageClient) HeartbeatRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, AzureMessage_HeartbeatRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AzureMessageServer is the server API for AzureMessage service.
// All implementations must embed UnimplementedAzureMessageServer
// for forward compatibility.
type AzureMessageServer interface {
	// Sends a heartbeat
	HeartbeatRequest(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAzureMessageServer()
}

// UnimplementedAzureMessageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAzureMessageServer struct{}

func (UnimplementedAzureMessageServer) HeartbeatRequest(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartbeatRequest not implemented")
}
func (UnimplementedAzureMessageServer) mustEmbedUnimplementedAzureMessageServer() {}
func (UnimplementedAzureMessageServer) testEmbeddedByValue()                      {}

// UnsafeAzureMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AzureMessageServer will
// result in compilation errors.
type UnsafeAzureMessageServer interface {
	mustEmbedUnimplementedAzureMessageServer()
}

func RegisterAzureMessageServer(s grpc.ServiceRegistrar, srv AzureMessageServer) {
	// If the following call pancis, it indicates UnimplementedAzureMessageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AzureMessage_ServiceDesc, srv)
}

func _AzureMessage_HeartbeatRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AzureMessageServer).HeartbeatRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AzureMessage_HeartbeatRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AzureMessageServer).HeartbeatRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AzureMessage_ServiceDesc is the grpc.ServiceDesc for AzureMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AzureMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocpp.v1.AzureMessage",
	HandlerType: (*AzureMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HeartbeatRequest",
			Handler:    _AzureMessage_HeartbeatRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/ocpp/v1/ocpp.proto",
}
