// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package schemas

import (
	"database/sql"
	"time"
)

type Chargepoint struct {
	SerialNumber      string
	Model             string
	Vendor            string
	FirmwareVersion   string
	Iicid             sql.NullString
	Imsi              sql.NullString
	MeterSerialNumber sql.NullString
	MeterType         sql.NullString
	LastBoot          time.Time
	LastHeartbeat     sql.NullTime
	LastConnected     sql.NullTime
}
