AZURE_SERVICE_BUS:
  CONNECTION_STRING: "Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
  TOPIC_INBOUND:
    NAME: "socket-events"
    SUBSCRIPTION: "socket-events-sub"
  TOPIC_OUTBOUND:
    NAME: "socket-commands"
    SUBSCRIPTION: "socket-commands-sub"
HTTP_SERVER:
  PORT: ":8082"
  HOST: "localhost"
