TELEMETRY:
  ENDPOINT: "localhost:4317"
AZURE_SERVICE_BUS:
  CONNECTION_STRING: "Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
  TOPIC_INBOUND:
    NAME: "socket-events"
    SUBSCRIPTION: "socket-events-sub"
  TOPIC_OUTBOUND:
    NAME: "socket-commands"
    SUBSCRIPTION: "socket-commands-sub"
DATABASE:
  DRIVER: "sqlite3"
  PROTOCOL: "file"
  ADDR: "/Users/ainsley.lee/tmp/ocpp.db"
